apiVersion: apps/v1
kind: Deployment
metadata:
  name: signup-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: signup-service
  template:
    metadata:
      labels:
        app: signup-service
    spec:
      containers:
        - name: signup-service
          image: nityahs/signup-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
