apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: finance-tracker
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: LoadBalancer
