apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage-service
  template:
    metadata:
      labels:
        app: homepage-service
    spec:
      containers:
        - name: homepage-service
          image: nityahs/homepage-service:latest  # Replace with actual image
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/financetracker"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
          ports:
            - containerPort: 8082
